---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "🏷️ Check/Inject Issue-ID"

outputs:
  PRESENT:
    description: "Whether the Issue-ID string is present"
    value: ${{ steps.fetch.outputs.count }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
       ref: ${{ github.event.pull_request.head.sha }}

    - name: Get commit message header
      id: get_commit_message
      shell: bash
      run: |
        COMMIT_MESSAGE_HEADER=$(git log -1 --pretty=%B | head -n 1)
        echo "COMMIT_MESSAGE_HEADER=${COMMIT_MESSAGE_HEADER}" >> $GITHUB_ENV

    - name: Use commit message header
      shell: bash
      run: |
        echo "The commit message header is: $COMMIT_MESSAGE_HEADER"

    - name: Get commit message header
      id: get_commit_message
      shell: bash
      run: |
        COMMIT_MESSAGE_HEADER=$(git log -1 --pretty=%B | head -n 1)
        echo "COMMIT_MESSAGE_HEADER=${COMMIT_MESSAGE_HEADER}" >> $GITHUB_ENV

    - name: Use commit message header
      shell: bash
      run: |
        echo "The commit message header is: $COMMIT_MESSAGE_HEADER"
        echo "Test"

    - name: "Checking for Issue-ID in body of first commit"
      id: check
      shell: bash
      run: |
        # Checking for Issue-ID in body of first commit
        echo "github.event.head_commit.message:"
        echo "${{ github.event.head_commit.message }}"
        echo "github.event.workflow_run.head_commit.message:"
        echo "${{ github.event.workflow_run.head_commit.message }}"
        echo "github.event.commits[0].message:"
        echo "${{ github.event.commits[0].message }}"

        # Gerrit reg-ex expression is:
        # Issue-ID: ([A-Z][A-Z0-9]{1,9}-\\d+)

        # Set detection outcome
        echo "present=false" >> "$GITHUB_ENV"
        echo "present=false" >> "$GITHUB_OUTPUT"

    - name: "Look up appropriate JIRA ticket for this change"
      id: lookup
      if: env.present == 'false'
      shell: bash
      run: |
        # Look up appropriate JIRA ticket for this change
        echo "Look up appropriate JIRA ticket for this change"

    - name: "Injecting Issue-ID into body of first commit message"
      id: inject
      if: env.present == 'false'
      shell: bash
      run: |
        # Injecting Issue-ID into body of first commit
        echo "Injecting Issue-ID into body of first commit"
