bff.access-control:
  ACTIONS_CREATE: [ portal_admin, portal_designer, portal_operator ]
  ACTIONS_GET: [ portal_admin, portal_designer, portal_operator ]
  ACTIONS_LIST: [ portal_admin, portal_designer, portal_operator ]
  ACTIVE_ALARM_LIST: [portal_admin, portal_designer, portal_operator]
  KEY_ENCRYPT_BY_USER: [portal_admin, portal_designer, portal_operator]
  KEY_ENCRYPT_BY_VALUE: [portal_admin, portal_designer, portal_operator]
  PREFERENCES_CREATE: [portal_admin, portal_designer, portal_operator]
  PREFERENCES_GET: [portal_admin, portal_designer, portal_operator]
  PREFERENCES_UPDATE: [portal_admin, portal_designer, portal_operator]
  ROLE_LIST: ["*"]
  USER_CREATE: [portal_admin, portal_designer, portal_operator]
  USER_DELETE: [portal_admin, portal_designer, portal_operator]
  USER_GET: [portal_admin, portal_designer, portal_operator]
  USER_LIST_AVAILABLE_ROLES: [portal_admin, portal_designer, portal_operator]
  USER_LIST_ROLES: [portal_admin, portal_designer, portal_operator]
  USER_LIST: [portal_admin, portal_designer, portal_operator]
  USER_UPDATE_PASSWORD: [portal_admin, portal_designer, portal_operator]
  USER_UPDATE_ROLES: [portal_admin, portal_designer, portal_operator]
  USER_UPDATE: [portal_admin, portal_designer, portal_operator]

