---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: 'GitHub2Gerrit Python'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      preserve_github_prs:
        description: "Do NOT close GitHub PRs after pushing to Gerrit"
        required: false
        default: false
        type: boolean
      allow_duplicates:
        description: "Allow duplicate changes to be raised in Gerrit"
        required: false
        default: false
        type: boolean

  pull_request_target:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.run_id }}"
  cancel-in-progress: true

jobs:
  github2gerrit:
    name: 'GitHub2Gerrit Python'
    permissions:
      contents: read
      pull-requests: write
      issues: write
    timeout-minutes: 12
    # yamllint disable rule:line-length
    uses: modeseven-lfreleng-actions/github2gerrit-action/.github/workflows/github2gerrit.yaml@main
    with:
        USE_PR_AS_COMMIT: true
        ISSUE_ID: "CIMAN-33"
        ALLOW_DUPLICATES: "${{ inputs.allow_duplicates }}"
        PRESERVE_GITHUB_PRS: "${{ inputs.preserve_github_prs }}"
    secrets:
        GERRIT_SSH_PRIVKEY_G2G: "${{ secrets.GERRIT_SSH_PRIVKEY_G2G }}"
