---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "🏷️ Check/Inject Issue-ID"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master
      - main

concurrency:
  # yamllint disable-line rule:line-length
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  issue-id:
    name: "Check/Inject Required Gerrit Issue-ID"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      pull-requests: write
    steps:
      # yamllint disable-line rule:line-length
      # - uses: modeseven-onap/portal-ng-bff/.github/actions/gerrit-issue-id-action@master
      - uses: ./.github/actions/gerrit-issue-id-action
